### ISSUE TITLE
npm run generate no longer works

### ISSUE THREAD

**Issue by stevemayne** [JacobSNGoodwin/nuxt-ghost-starter#10]
All pages that `npm run generate` attempts to create throw the following exception:

```
 ERROR   /the-editor                                                           13:54:36

TypeError: e is not a function
    at Store.nuxtServerInit (webpack/bootstrap:2:0)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

to replicate:

```
git clone x
npm install
npm run generate
```

**Comment by stevemayne** [comment]
This is a breaking change somewhere between:

`"nuxt": "^2.4.0"` and `"nuxt": "^2.8.1"`

**Comment by JacobSNGoodwin** [comment]
@stevemayne, thanks for spotting this problem!

I believe the issue was that I was destructuring _error_ from the first argument of nuxtServerInit, while it should be destructured from the second argument as explained [here](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action).

I'll create a PR and merge (since it needs to be fixed anyway), but also let me know if this worked for you.

maxbrain0/nuxt-ghost-starter@89120ce34c2246dd7bbb148c9da0a7cd52fc4826

**Comment by stevemayne** [comment]
@Maxbrain0 Good work! I now get the following error on each page (when running generate), which may or may not be related to the former problem:

```

 ERROR   /                                                                                                                                                                           19:50:44

TypeError: Cannot read property 'logo' of null
    at a.tt.components.Navigation (webpack/bootstrap:2:0)
    at a.t._render (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70663
    at Yi (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67227)
    at io (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70639)
    at ro (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70270)
    at _t.eo [as renderNode] (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67517)
    at _t.next (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:20536)
    at n (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:18748)
    at /Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:68628
    at eo (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:68636)
    at /Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70737
    at Yi (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67227)
    at io (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70639)
    at ro (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70270)
    at _t.eo [as renderNode] (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67517)
```

It looks like settings isn't being passed into the Navigation component

**Comment by JacobSNGoodwin** [comment]
@stevemayne, I created a separate issue and will close this one. 

Unfortunately, I have not been able to get this to occur on my end yet and the root page is successfully generated. Let me know in #12 if you find any more hints that may be helpful in solving the issue. I'll toy around for a few minutes to see what I can find.
