### ISSUE TITLE
Settings not passed to navigation component

### ISSUE THREAD

**Issue by JacobSNGoodwin** [JacobSNGoodwin/nuxt-ghost-starter#12]
@Maxbrain0 Good work! I now get the following error on each page (when running generate), which may or may not be related to the former problem:

```

 ERROR   /                                                                                                                                                                           19:50:44

TypeError: Cannot read property 'logo' of null
    at a.tt.components.Navigation (webpack/bootstrap:2:0)
    at a.t._render (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70663
    at Yi (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67227)
    at io (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70639)
    at ro (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70270)
    at _t.eo [as renderNode] (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67517)
    at _t.next (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:20536)
    at n (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:18748)
    at /Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:68628
    at eo (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:68636)
    at /Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70737
    at Yi (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67227)
    at io (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70639)
    at ro (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:70270)
    at _t.eo [as renderNode] (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/vue-server-renderer/build.prod.js:1:67517)
```

It looks like settings isn't being passed into the Navigation component

_Originally posted by @stevemayne in https://github.com/Maxbrain0/nuxt-ghost-starter/issues/10#issuecomment-544187388_

**Comment by JacobSNGoodwin** [comment]
@stevemayne I haven't been able to recreate this problem. If you find anything that you think may be causing this, let me know. And for your information.

Settings is passed to [components/Navigation.vue](https://github.com/Maxbrain0/nuxt-ghost-starter/blob/master/components/Navigation.vue) via props from the  [Default](https://github.com/Maxbrain0/nuxt-ghost-starter/blob/master/layouts/default.vue) layout. This gets the siteSettings from the vuex [store](https://github.com/Maxbrain0/nuxt-ghost-starter/blob/master/store/index.js), which loads site settings from ghost in nuxtServerInit.

So maybe there's an issue connecting to your Ghost Blog's API. 

I have a .env.example file in the repository root.  Be sure to include your own Ghost URI and Key in the file and rename the file to .env.

I don't know if will fix your problem, but I do believe it's an issue connecting the your ghost API.

**Comment by stevemayne** [comment]
@Maxbrain0 I'll spend some time working out what's going on. I have cloned fresh from the repo again and I get the same error. I must be able to connect to the Ghost API as it's picking up my post slugs. No problems though - I need more practice at debugging JavaScript, so I'll see whether I can work it out. 

Thanks for creating this project by the way, it's been a huge help.

**Comment by stevemayne** [comment]
@Maxbrain0 Swallowing exceptions in the nuxtServerInit function seems to be the wrong thing to do when in a `generate` context. I changed the exception handler to re-throw the exception:

```javascript
    } catch (e) {
      // since this is server init, the error would be a server error
      error({ statusCode: 500, message: e.message })
      throw e
    }
```

This gives visibility of the failure, and stops Nuxt carrying on with the page generation:

```
 ERROR   /publishing-options                                                                                                                                                         10:36:51

Error: Request failed with status code 429
    at createError (/Users/steve/git/fh/nuxt-ghost-starter/node_modules/@tryghost/content-...
```

I don't know how this will affect server-side generation (when you want to return a 500 error page using the error() function) - although I suspect it will do this anyway if nuxtServerInit throws an exception.

**Comment by mskian** [comment]
@Maxbrain0 For me it Generates the static pages without Errors

**Comment by stevemayne** [comment]
@mskian @Maxbrain0 The problem occurs if the API throws an exception. The exception is swallowed meaning the rendering process may or may not work - but the error won't directly relate to the data-fetch failure. If the site is being generated in a CI/CD stack, visibility of errors is essential, as otherwise you could push a non-working version of the site.

**Comment by mskian** [comment]
@stevemayne yes off course

I tried this 
also tested on travis-ci

```js
catch (e) {
      // since this is server init, the error would be a server error
      error({ statusCode: 500, message: e.message })
      throw e
    }
```
Generate without errors

**Comment by JacobSNGoodwin** [comment]
@stevemayne, Thanks for finding the simple fix, for your explanation, and for contributing to what was a resume-building project.
